apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p81s3s6pt-java-quarkus
  janus-idp.io/tekton: p81s3s6pt-java-quarkus
  backstage.io/kubernetes-id: p81s3s6pt-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p81s3s6pt-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
